### ISSUE TITLE
Fix problem when None is returned in country_code

### ISSUE THREAD

**Issue by HallBregg** [HallBregg/just-greep#7]
`Traceback (most recent call last):
app_service |   File "main.py", line 200, in <module>
app_service |     handle(debug, cursor, count_limit=None)
app_service |   File "main.py", line 111, in handle
app_service |     'country': offer_detail.get('country_code').lower(),
app_service | AttributeError: 'NoneType' object has no attribute 'lower'`

**Comment by HallBregg** [comment]
#9
